# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot.initrd.availableKernelModules = [
    "virtio_pci"
    "virtio_blk"
    "virtio_scsi"
    "virtio_net"
    "xhci_pci"
    "sr_mod"
    "ahci"
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm" "virtio" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
    autoResize = true;
  };

  fileSystems."/home" = {
    device = "/dev/vdb";
    fsType = "ext4";
    # Only mount /home on vdb when it exists (not building the base image)
    options = [ "defaults" "nofail" "x-systemd.device-timeout=1" ];
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;
  #networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}

