# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot.initrd.availableKernelModules = [
    "virtio_pci"
    "virtio_blk"
    "virtio_scsi"
    "virtio_net"
    "xhci_pci"
    "sr_mod"
    "ahci"
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm" "virtio" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/vda";
    fsType = "ext4";
  };

  # Only mount /home on vdb when NOT building a disk image
  fileSystems."/home" = lib.mkIf (!config.system.build ? qcow2) {
    device = "/dev/vdb";
    fsType = "ext4";
    options = [ "defaults" ];
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}

